# Generated by Django 3.2.4 on 2021-08-02 14:21

import cloudinary_storage.storage
from django.db import migrations, models
import fpc_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User messages',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('position_number', models.PositiveBigIntegerField()),
                ('content', models.TextField()),
                ('qualifications', models.TextField(blank=True, help_text='Enter qualifications separated by a comma after each qualification', null=True)),
                ('filefield', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=fpc_api.models.get_file_name)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to=fpc_api.models.get_file_name)),
                ('image_info', models.CharField(max_length=500)),
                ('news_content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to=fpc_api.models.get_file_name)),
                ('position', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
