# Generated by Django 3.2.4 on 2021-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter subscribers',
            },
        ),
    ]
