# Generated by Django 3.2.4 on 2021-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0002_alter_jobs_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.ImageField(upload_to='teamMembers'),
        ),
    ]
