# Generated by Django 3.2.4 on 2021-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0003_auto_20210730_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='filefield',
            field=models.FileField(upload_to='jobs/<function get_file_name at 0x000001D7F4B8DD30>'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news/<function get_file_name at 0x000001D7F4B8DD30>'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.ImageField(upload_to='teamMembers/<function get_file_name at 0x000001D7F4B8DD30>'),
        ),
    ]
