# Generated by Django 3.2.4 on 2021-07-30 20:12

from django.db import migrations, models
import fpc_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0004_auto_20210730_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='filefield',
            field=models.FileField(upload_to=fpc_api.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to=fpc_api.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.ImageField(upload_to=fpc_api.models.get_file_name),
        ),
    ]
