# Generated by Django 3.2.4 on 2021-07-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0005_auto_20210730_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'User messages'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
