# Generated by Django 3.2.4 on 2021-07-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0006_auto_20210730_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
