# Generated by Django 3.2.4 on 2021-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0007_jobs_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Enter qualifications separated by a comma after each qualification', null=True),
        ),
    ]
