# Generated by Django 3.2.4 on 2021-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0008_alter_jobs_qualifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'User messages'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
