# Generated by Django 3.2.4 on 2021-08-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0009_auto_20210731_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
