# Generated by Django 3.2.4 on 2021-08-01 21:02

import cloudinary_storage.storage
from django.db import migrations, models
import fpc_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('fpc_api', '0010_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='filefield',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=fpc_api.models.get_file_name),
        ),
    ]
